import { Controller, Get, Param } from '@nestjs/common';
import { QuotesService } from './quotes.service';

// No JwtAuthGuard/RolesGuard on purpose — this is the client-facing link
// generated by QuotesService.update when a quote is marked SENT. The random
// token in the URL is the access control.
@Controller('public/quotes')
export class PublicQuotesController {
  constructor(private readonly quotesService: QuotesService) {}

  @Get(':token')
  findByToken(@Param('token') token: string) {
    return this.quotesService.findByShareToken(token);
  }
}
